[package]
name = "bunkr-scraper"
version = "0.1.0"
edition = "2024"

[dependencies]
regex = "1.11.1"
reqwest = "0.12.20"
serde_json = "1.0.140"
thirtyfour = "0.35.0"
tokio = { version = "1.45.1", features = ["full"] }
